### ISSUE TITLE
ES6 build not working

### ISSUE THREAD

**Issue by therepo90** [kristianmandrup/bitbucket-auth#5]
Can not make it work. Its not build for ES5, injecting babel did not help. Manual npm run build won't work either

**Comment by kristianmandrup** [comment]
Sorry. Try cloning and running tests then figuring out a way to build it that works for you. I've never used it in a real project myself unfortunately.

**Comment by kristianmandrup** [comment]
Fixing now: `package.json` to `"main": "dist/bitbucketAuth.min.js",`
Also see #4

**Comment by kristianmandrup** [comment]
Released new version on npm that should work. Also ran `npm audit fix` to fix security vulnerabilities.
Please try again ;)
